= BookWhale API Docs
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4

== 상태 코드

API 공통적으로 사용되는 상태 코드이다.

|===
| 상태 코드(Status code) | 용례(Usage)

| `200 OK`
| 요청을 성공적으로 처리함.

| `201 CREATED`
| 요청한 리소스가 성공적으로 생성됨.

| `400 BAD_REQUEST`
| 잘못된 요청을 보낸 경우.
응답 본문에 오류에 대한 정보가 담겨있다.

| `401 UNAUTHORIZED`
| 요구되는 인증 정보가 없어 접근이 거부된 경우.

| `404 NOT_FOUND`
| 요청한 리소스가 없음.

| `405 METHOD_NOT_ALLOWED`
| 잘못된 HTTP 메소드로 요청한 경우.
|===

== 1. 유저

=== 1.1 회원가입

operation::user/signup[snippets='http-request,request-fields,http-response']

=== 1.2 로그인

operation::user/userLogin[snippets='http-request,request-fields,http-response']

=== 1.3 내 정보 조회

operation::user/me[snippets='http-request,request-headers,http-response']

=== 1.4 내 정보 수정

operation::user/updateMe[snippets='http-request,request-headers,request-fields,http-response']

=== 1.5 비밀번호 수정

operation::user/updatePassword[snippets='http-request,request-headers,request-fields,http-response']

=== 1.6 프로필 업로드

operation::user/uploadProfileImage[snippets='http-request,request-headers,request-parts,http-response,response-fields']

=== 1.7 프로필 삭제

operation::user/deleteProfileImage[snippets='http-request,request-headers,http-response']

=== 1.8 관심목록 추가

operation::user/addLike[snippets='http-request,request-headers,request-fields,http-response']

=== 1.9 관심목록 조회

operation::user/findLikes[snippets='http-request,request-headers,http-response,response-fields']

=== 1.10 관심목록 삭제

operation::user/deleteLike[snippets='http-request,request-headers,path-parameters,http-response']

=== 1.11 내 게시글 조회

operation::user/findMyPosts[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

== 2. 게시글

=== 2.1 네이버 책 API

operation::post/findNaverBooks[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== 2.2 게시글 등록

operation::post/createPost[snippets='http-request,request-headers,request-part-postRequest-fields,http-response']

=== 2.3 게시글 상세 조회

operation::post/findPost[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

=== 2.4 게시글 전체 조회

operation::post/findPosts[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== 2.5 게시글 수정

게시글 수정 API 는 문서화 X => 직접 물어봐주세요..

=== 2.6 게시글 상태 변경

operation::post/updatePostStatus[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

=== 2.7 판매글 검색조건 - 판매상태

operation::post/conditions/bookStatus[snippets='http-request,http-response,response-fields']

=== 2.8 판매글 검색조건 - 판매지역
* 설정된 판매지역은 대한민국의 17개 행정 구역을 기준으로 생성하였습니다.
** https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD%EC%9D%98_%ED%96%89%EC%A0%95_%EA%B5%AC%EC%97%AD[위키백과 - 대한민국의 행정 구역]

operation::post/conditions/locations[snippets='http-request,http-response,response-fields']

== 3. 채팅

=== 3.1 채팅방 생성

operation::chatRoom/createChatRoom[snippets='http-request,request-headers,request-fields,http-response']

=== 3.2 채팅방 목록 조회

operation::chatRoom/findChatRooms[snippets='http-request,request-headers,http-response,response-fields']

=== 3.3 채팅방 삭제

operation::chatRoom/deleteChatRoom[snippets='http-request,request-headers,path-parameters,http-response']