= BookWhale API Docs
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4

== 상태 코드

API 공통적으로 사용되는 상태 코드이다.

|===
| 상태 코드(Status code) | 용례(Usage)

| `200 OK`
| 요청을 성공적으로 처리함.

| `201 CREATED`
| 요청한 리소스가 성공적으로 생성됨.

| `400 BAD_REQUEST`
| 잘못된 요청을 보낸 경우.
응답 본문에 오류에 대한 정보가 담겨있다.

| `401 UNAUTHORIZED`
| 요구되는 인증 정보가 없어 접근이 거부된 경우.

| `404 NOT_FOUND`
| 요청한 리소스가 없음.

| `405 METHOD_NOT_ALLOWED`
| 잘못된 HTTP 메소드로 요청한 경우.
|===

== 오류 코드
API를 호출할 때 예외를 던지는 경우에 사용되는 코드이다.

=== Status 500
|===
| 오류 코드(Error code) | 용례(Usage) | 메시지(Response)

| `S_001`
| 서버에서 오류가 발생되는 경우 (대비되지 않은 예외 발생, 서버 장애 등)
| ```{
"status": 500,
"message": "서버에 문제가 생겼습니다.",
"code": "S_001",
"errors": null
} ```

| `S_003`
| 네이버 책 API 서버 사용하는 과정에서의 오류 발생 시
| ```{
"status": 500,
"message": "네이버 책 API 서버에 문제가 생겼습니다.",
"code": "S_003",
"errors": null
} ```

| `S_004`
| XML 파일을 변환하는 과정에서의 오류 발생 시
| ```{
"status": 500,
"message": "XML 파일을 변환하는 과정에서 문제가 발생했습니다.",
"code": "S_004",
"errors": null
} ```

| `S_005`
| JSON 형식으로 변환하는 과정에서의 오류 발생 시
| ```{
"status": 500,
"message": "JSON 형식으로 변환하는 과정에서 문제가 발생했습니다.",
"code": "S_005",
"errors": null
} ```
|===

=== Status 400
|===
| 오류 코드(Error code) | 용례(Usage) | 메시지(Response)

| `AU_001`
| 로그인 없이 컨텐츠에 접근하는 경우
| ```{
"status": 401,
"message": "해당 콘텐츠에 접근 권한이 없는 유저입니다.",
"code": "AU_001",
"errors": null
} ```

| `AU_002`
| 로그인 없이 redirect 된 경우
| ```{
"status": 400,
"message": "인증되지 않은 REDIRECT_URI 입니다.",
"code": "AU_002",
"errors": null
} ```

| `C_001`
| 적절하지 않은 요청(request)을 받은 경우
| ```{
"status": 400,
"message": "적절하지 않은 요청 값입니다.",
"code": "C_001",
"errors": null
} ```

| `C_002`
| 적절하지 않은 요청(request)을 받은 경우
| ```{
"status": 400,
"message": "요청 값의 타입이 잘못되었습니다.",
"code": "C_002",
"errors": null
} ```

| `C_003`
| multipart/form-data 활용 시 requestPart를 확인할 수 없는 경우
| ```{
"status": 400,
"message": "RequestPart는 필수 값입니다.",
"code": "C_003",
"errors": null
} ```

| `C_004`
| 잘못된 http Method로 요청하는 경우
| ```{
"status": 405,
"message": "적절하지 않은 HTTP 메소드입니다.",
"code": "C_001",
"errors": null
} ```

| `U_001`
| 이미 존재하는 사용자인 경우
| ```{
"status": 400,
"message": "이미 존재하는 아이디입니다.",
"code": "U_001",
"errors": null
} ```

| `U_002`
| 요청한 사용자 정보가 조회되지 않은 경우 (서버 오류 제외)
| ```{
"status": 404,
"message": "요청한 사용자 정보를 확인할 수 없습니다.",
"code": "U_002",
"errors": null
} ```

| `A_001`
| 대상 게시글의 ID가 유효하지 않은 값인 경우
| ```{
"status": 400,
"message": "잘못된 게시글 ID 입니다.",
"code": "A_001",
"errors": null
} ```

| `A_002`
| 대상 게시글이 존재하지 않는 경우
| ```{
"status": 400,
"message": "존재하지 않는 게시글 ID 입니다.",
"code": "A_002",
"errors": null
} ```

| `A_003`
| 판매글이 없는 상태에서 채팅 기능을 요청한 경우
| ```{
"status": 400,
"message": "판매중인 게시글만 판매자에게 채팅을 보낼 수 있습니다.",
"code": "A_003",
"errors": null
} ```

| `A_004`
| 판매글 (ArticleStatus = SALE)이 아닌 상태에서 삭제를 요청한 경우
| ```{
"status": 400,
"message": "판매중인 게시글만 삭제할 수 있습니다.",
"code": "A_004",
"errors": null
} ```



| `I_001`
| 대상 관심 판매글의 ID가 유효하지 않은 값인 경우
| ```{
"status": 400,
"message": "잘못된 관심목록 ID 입니다.",
"code": "I_001",
"errors": null
} ```

| `I_002`
| 이전에 관심 판매글로 등록된 판매글인 경우 (중복)
| ```{
"status": 400,
"message": "이미 관심목록에 등록된 게시글입니다.",
"code": "I_002",
"errors": null
} ```

| `I_003`
| 판매글에 관심목록(좋아요) 정보가 조회되지 않는 경우
| ```{
"status": 404,
"message": "관심목록 ID를 찾을 수 없습니다.",
"code": "I_003",
"errors": null
} ```

| `CHAT_001`
| 대상 채팅방 ID가 유효하지 않은 값인 경우
| ```{
"status": 400,
"message": "잘못된 채팅방 ID 입니다.",
"code": "CHAT_001",
"errors": null
} ```

| `CHAT_002`
| 대상 판매자 ID가 유효하지 않은 값인 경우
| ```{
"status": 400,
"message": "잘못된 판매자 ID 입니다.",
"code": "CHAT_002",
"errors": null
} ```

| `T_001`
| 토큰(Token) 형식이 유효하지 않은 경우
| ```{
"status": 400,
"message": "유효하지 않은 토큰 입니다.",
"code": "T_001",
"errors": null
} ```

| `T_002`
| OAuth Provider로부터 인증 실패된 경우 (유효한 접근 권한을 확인하지 못함)
| ```{
"status": 401,
"message": "OAuth 로그인 인증에 실패하였습니다.",
"code": "T_002",
"errors": null
} ```

| `T_003`
| OAuth Provider로부터 받은 접근 권한(AccessToken)으로 조회하지 못한 경우
| ```{
"status": 404,
"message": "OAuth 요청으로 요청한 정보를 불러오지 못했습니다.",
"code": "T_003",
"errors": null
} ```

| `T_004`
| 요청 시 확인된 ApiToken 으로 API 기능을 요청할 수 없는 경우 (토큰 만료 등)
| ```{
"status": 403,
"message": "권한을 확인할 수 없습니다.",
"code": "T_004",
"errors": null
} ```
|===

== 1. 사용자 인증 관련 (OAuth)
- OAuth Provider로는 google, naver, kakao를 설정하였음.
- provider로부터 사용자 정보를 요청할 수 있다.

=== 1.1.1 로그인 (web용, redirect 방식)
- provider에 로그인 요청 (네이버에 로그인 요청 시)

operation::oauth/requestLogin[snippets='http-request,http-response']

- 로그인 후 api token 생성 요청 (redirect)

operation::oauth/loginProcessAfterRedirct[snippets='http-request,http-response,response-fields']

=== 1.1.2 로그인 (provider의 accessToken으로 요청 시)
- accessToken으로 api token 생성 요청

operation::oauth/loginProcess[snippets='http-request,path-parameters,request-parameters,http-response,response-fields']

=== 1.2 토큰 갱신 (refresh)

operation::oauth/refresh[snippets='http-request,http-response,response-fields']

=== 1.3 로그아웃

operation::oauth/logout[snippets='http-request,request-headers,http-response,response-fields']

=== 1.4 회원탈퇴

operation::oauth/withdrawal[snippets='http-request,request-headers,http-response,response-fields']

== 2. 유저

=== 2.1 내 정보 수정

operation::user/updateMe[snippets='http-request,request-headers,request-fields,http-response']

=== 2.2 프로필 업로드

operation::user/uploadProfileImage[snippets='http-request,request-headers,request-parts,http-response,response-fields']

=== 2.3 프로필 삭제

operation::user/deleteProfileImage[snippets='http-request,request-headers,http-response']

=== 2.4 관심목록 추가

operation::user/addFavorite[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== 2.5 관심목록 조회

operation::user/findFavorites[snippets='http-request,request-headers,http-response,response-fields']

=== 2.6 관심목록 삭제

operation::user/deleteFavorite[snippets='http-request,request-headers,path-parameters,http-response']

=== 2.7 내 판매글 조회

operation::user/findMyArticles[snippets='http-request,request-headers,http-response,response-fields']

=== 2.8 내 정보 조회

operation::user/me[snippets='http-request,request-headers,http-response,response-fields']

=== 2.9 push 설정 조회

operation::user/getPushSetting[snippets='http-request,request-headers,http-response,response-fields']

=== 2.10 push 설정 변경 (Toggle)

operation::user/updatePushSetting[snippets='http-request,request-headers,http-response,response-fields']

== 3. 판매글

=== 3.1 네이버 책 API

operation::article/findNaverBooks[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== 3.2 판매글 등록

operation::article/createArticle[snippets='http-request,request-headers,request-part-articleRequest-fields,http-response']

=== 3.3 판매글 상세 조회

operation::article/findArticle[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

=== 3.4 판매글 전체 조회

operation::article/findArticles[snippets='http-request,request-parameters,http-response,response-fields']

=== 3.5 판매글 수정

※ 이미지(images)는 판매글 등록(3.2)하고 동일합니다(아래 예시에는 이미지 정보가 안들어가지네요).

※ Request part-articlerequest-fields -> Request part-articleUpdaterequest-fields로 변경됐습니다.

※Request part-articleUpdaterequest-fields은 아래를 참고해주시면 됩니다.

operation::article/updateArticle[snippets='http-request,request-headers,request-part-articleUpdateRequest-fields,http-response']

=== 3.6 판매글 상태 변경

operation::article/updateArticleStatus[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

=== 3.7 판매글 검색조건 - 판매상태

operation::article/conditions/bookStatus[snippets='http-request,http-response,response-fields']

=== 3.8 판매글 검색조건 - 판매지역
* 설정된 판매지역은 대한민국의 17개 행정 구역을 기준으로 생성하였습니다.
** https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD%EC%9D%98_%ED%96%89%EC%A0%95_%EA%B5%AC%EC%97%AD[위키백과 - 대한민국의 행정 구역]

operation::article/conditions/locations[snippets='http-request,http-response,response-fields']

=== 3.9 판매글 삭제
* 판매글 삭제는 아래의 제약조건을 가집니다.
** 삭제하려는 판매글은 사용자 본인이 등록한 판매글이어야 합니다. (myArticle = true)
** 상태가 [판매중]인 판매글만 가능합니다. (articleStatus = SALE)
* 판매글이 삭제 처리되면 아래의 동작에서 확인되지 않습니다.
** 판매글 목록 조회
** 관심글 목록 조회
** 내 판매글 목록 조회

operation::article/deleteArticle[snippets='http-request,request-headers,path-parameters,http-response']

== 4. 채팅 (API)

=== 4.1 채팅방 생성

operation::chatRoom/createChatRoom[snippets='http-request,request-headers,request-fields,http-response']

=== 4.2 채팅방 목록 조회

operation::chatRoom/findChatRooms[snippets='http-request,request-headers,http-response,response-fields']

=== 4.3 채팅방 삭제
* (권장사항) websocket 세션이 종료(close)되도록 요청 후 채팅방 삭제를 요청해주세요.
** websocket 종료에 대한 정보는 아래 링크들을 참조해주세요.
*** https://stomp.github.io/stomp-specification-1.2.html#DISCONNECT
*** https://stackoverflow.com/questions/4812686/closing-websocket-correctly-html5-javascript

* 최신 브라우저의 경우 브라우저 종료 시 세션이 종료되도록 설정되는 것으로 보입니다.
** https://developer.mozilla.org/ko/docs/web/api/websockets_api/writing_websocket_client_applications

* StompProtocolAndroid 에서는 아래와 같이 세션을 종료할 수 있습니다.
** https://github.com/NaikSoftware/StompProtocolAndroid#example-library-usage
----
    mStompClient.disconnect();
----



operation::chatRoom/deleteChatRoom[snippets='http-request,request-headers,path-parameters,http-response']

=== 4.4 채팅방 이전 메시지 조회

==== HTTP request
[source,http,options="nowrap"]
----
GET /api/message/1?page=0&size=10 HTTP/1.1
Host: localhost:8081

----

==== Path parameters
.+/api/message/{roomId}+
|===
|Parameter|Description

|`+roomId+`
|채팅방 ID

|===

==== Request parameters
|===
|Parameter|Description

|`+page+`
|이전 채팅 내용 DB 조회 시 offset

|`+size+`
|이전 채팅 내용 DB 조회 시 limit

|===

==== HTTP response
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: 142

[ {
  "senderId" : 1,
  "senderIdentity" : "highright96",
  "content" : "안녕하세요.",
  "createdDate" : "2022-01-28T23:00:06.771899"
} ]
----

==== Response Fields
|===
|Path|Type|Description

|`+[].senderId+`
|`+Number+`
|메시지를 전송한 사용자 ID

|`+[].senderIdentity+`
|`+String+`
|메시지를 전송한 사용자 이름

|`+[].content+`
|`+String+`
|메시지 내용

|`+[].createdDate+`
|`+String+`
|메시지 생성일

|===

=== 4.5 채팅방 마지막 메시지 조회

==== HTTP request
[source,http,options="nowrap"]
----
GET /api/message/1/last HTTP/1.1
Host: localhost:8081

----

==== Path parameters
.+/api/message/{roomId}/last+
|===
|Parameter|Description

|`+roomId+`
|채팅방 ID

|===

==== HTTP response
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: 138

{
  "senderId" : 1,
  "senderIdentity" : "highright96",
  "content" : "안녕하세요.",
  "createdDate" : "2022-01-29T13:41:16.172379"
}
----

==== Response Fields

|===
|Path|Type|Description

|`+senderId+`
|`+Number+`
|메시지를 전송한 사용자 ID

|`+senderIdentity+`
|`+String+`
|메시지를 전송한 사용자 이름

|`+content+`
|`+String+`
|메시지 내용

|`+createdDate+`
|`+String+`
|메시지 생성일

|===


== 5. 채팅 (CHAT)
=== 참고자료
- 웹 소켓에 대해 : https://tecoble.techcourse.co.kr/post/2021-09-05-web-socket-practice/
- spring-guides/stomp-websocket : https://github.com/spring-guides/gs-messaging-stomp-websocket
- spring Web MVC - WebSocket : https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#websocket
- spring WebSocket - SockJS와 STOMP : https://supawer0728.github.io/2018/03/30/spring-websocket/

=== 5.1 채팅방 WebSocket 기본 설정
- source : `http://localhost:8081/ws`
- sockJS 설정 : new SockJS("http://localhost:8081/ws");
    - `ws://` 또는 `wss://` 로 호출 (wss 권장)

=== 5.2 채팅방 접속
==== WebSocket request
----
STOMP /sub/chat/room/1 HTTP/1.1
Host: localhost:8081
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Protocol: ws
----

==== Path parameters
.+/sub/chat/room/{roomId}+
|===
|Parameter|Description

|`+roomId+`
|채팅방 ID

|===

=== 5.3 채팅방 메시지 전송

==== WebSocket request
[source,http,options="nowrap"]
----
STOMP /pub/chat/message HTTP/1.1
Host: localhost:8081
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Protocol: ws
Content-Type: application/json;charset=UTF-8

{
  "roomId" : 1,
  "senderId" : 1,
  "senderIdentity" : "highright96",
  "content" : "Hello, World!"
}
----

==== Request parameters
|===
|Parameter|Description

|`+roomId+`
|subscribe 된 채팅방 ID

|`+senderId+`
|채팅을 전송한 사용자 ID

|`+senderIdentity+`
|채팅을 전송한 사용자 이름

|`+content+`
|채팅 내용
|===

=== 5.4 채팅방 메시지 전송 시 push message
* 메시지 전송은 FCM 을 활용하였습니다.
** https://firebase.blog/posts/2017/11/whats-new-with-fcm-customizing-messages
** https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages
* 메시지를 전송하면 채팅방에 속해있는 상대방(판매자 또는 구매자)에게 아래의 형식으로 메시지가 전송됩니다.
----
"message":{
    "token":"bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...",
    "data" : {
      "articleTitle" : "책 팝니다",
      "roomId" : "1"
      "senderId" : "2",
      "description" : "안녕하세요."
    }
  }
}
----

==== Push message parameters
|===
|Parameter|Description

|`+token+`
|로그인시 등록된 기기 토큰

|`+data.articleTitle+`
|판매글 제목

|`+data.roomId+`
|생성된 채팅방 ID

|`+data.senderId+`
|메시지를 전송한 사용자 ID

|`+data.description+`
|전송한 메시지

|===
